title: Kolade Olusola # your name (or website title) here
logo: "/images/Logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate of English Education turned Software Engineer with a reasonable experience building responsive web applications and Restful APIs
  <br><br>
  Proficient in the MERN stack and the PERN stack
  <br><br>
  <a href="https://www.linkedin.com/in/kolade-olusola-623b00148/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
